name: Test Avalex against TYPO3 6-10

on: [pull_request]

jobs:
  testing:
    name: PHP Unit and Functional Tests

    runs-on: ubuntu-latest

    strategy:
      matrix:
        typo3: [ '^9.5', '^10.4' ]
        php: [ '7.3', '7.4' ]
        package: [typo3/cms-core]
        include:
          - typo3: '^6.2'
            php: '5.6'
            composer: '1'
            package: typo3/cms
          - typo3: '^7.6'
            php: '5.6'
            composer: '1'
            package: typo3/cms
          - typo3: '^7.6'
            php: '7.0'
            composer: '1'
            package: typo3/cms
          - typo3: '^8.7'
            php: '7.0'
            composer: '1'
          - typo3: '^8.7'
            php: '7.1'
            composer: '1'
          - typo3: '^8.7'
            php: '7.2'
            composer: '1'
    services:
      mysql:
        image: mysql:5.6
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up PHP version ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Use correct composer version for specific TYPO3 version
        run: |
          composer self-update --${{ matrix.composer }}

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies with ${{ matrix.package }}:${{ matrix.typo3 }}
        run: |
          composer require ${{ matrix.package }}:${{ matrix.typo3 }} --no-progress
          composer require typo3/cms-extensionmanager:^10.4 --no-progress
          composer require --dev nimut/testing-framework:">=2.0" phpunit/phpunit:"<9.0" phpspec/prophecy:^1.10 --no-progress
          git checkout composer.json

      - name: Functional Tests
        if: matrix.php > 7.0
        env:
          typo3DatabaseName: test
          typo3DatabaseUsername: root
          typo3DatabasePassword: password
          typo3DatabaseHost: 127.0.0.1
          typo3DatabasePort: ${{ job.services.mysql.ports['3306'] }}
        run: |
          composer ci:tests:functional
